default:
  image: node:22

stages:
  - version


version:
  stage: version
  script:
    - yarn install
    - yarn semantic-release
  variables:
    GITLAB_TOKEN: $PAT_SEMANTIC_RELEASE
  only:
    - main
