# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Symfony

on:
  push:
    branches:
      - dev
      - main

jobs:
  deployDevelopmentJob:
    if: github.ref == 'refs/heads/dev'
    environment: dev
    env:
      SSH_PRIVATE_KEY: ${{ secrets.DEPLOYMENT_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH agent and add key
        run: |
          which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
          mkdir -p ~/.ssh
          [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          

      - name: Add Server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan 116.202.22.113 >> ~/.ssh/known_hosts

      - name: Run Envoy Deployment
        run: |
          # Run the Envoy deployment command using the determined environment
          ~/.composer/vendor/bin/envoy run deploy \
          --environment=dev \
          --secret=${{ secrets.DEV_DECRYPTION_KEY }}
