# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Symfony

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          log-public-key: true

      - name: Add Server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan 116.202.22.113 >> ~/.ssh/known_hosts

      - name: Setup Php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, dom
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run Envoy Deployment
        run: |
          # Extract the branch name from GITHUB_REF
          BRANCH_NAME=${GITHUB_REF##*/}
          echo "Deploying branch: ${BRANCH_NAME}"
          
          # Decide deployment environment: main -> prod, otherwise dev
          if [ "${BRANCH_NAME}" = "main" ]; then
            ENV="prod"
          else
            ENV="dev"
          fi
          echo "Deploying to the '${ENV}' environment"
          
          # Run the Envoy deployment command using the determined environment
          vendor/bin/envoy run deploy --environment=$ENV
